title: "ToolsClouds"
description: "All-in-one online calculators, converters, and generators"
url: "https://toolclouds.com"
baseurl: ""

collections:
  tools:
    output: true
    permalink: /:categories/:name/

defaults:
  - scope:
      path: ""
      type: "tools"
    values:
      layout: tool
