title: "ToolsClouds"
description: "All-in-one online calculators, converters, and generators"
url: "https://toolclouds.com"
baseurl: ""

collections:
  tools:
    output: true
    permalink: /:categories/:name/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

author:
  name: "ToolClouds"
  email: "manjeetsingh.codes@gmail.com"


defaults:
  - scope:
      path: ""
      type: "tools"
    values:
      layout: tool
