title: "ToolsClouds"
description: "All-in-one online calculators, converters, and generators"
baseurl: "" 
url: "https://manjeetcodes0.github.io/toolclouds/"

collections:
  tools:
    output: true
    permalink: /:categories/:name/

defaults:
  - scope:
      path: ""
      type: "tools"
    values:
      layout: tool
